apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-frontend-html
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8"/>
        <title>Talos lab demo</title>
      </head>
      <body>
        <h1>âœ… Talos/Kubernetes demo-frontend</h1>
        <p>Hvis du ser denne siden via Ubuntu:8080, er port-forward-kjeden OK.</p>
      </body>
    </html>
